### ISSUE TITLE
Problem appending strings to a bcolz array

### ISSUE THREAD

**Issue by mpage38** [Blosc/bcolz#250]
When appending strings to a bcolz array with the following code:

    bz = bcolz.carray(np.array([], dtype="S500"))
    for i in range(1000):
        bz.append(np.array(["xxx"]))
        if len(bz) >= 2 and type(bz[1]) == np.ndarray:
            print("oops")

at some point (actually when i == bz.chunklen), the elements of the bz array have their 'bytes' type changed and become 'ndarray'.

If I specify: bz = bcolz.carray(np.array([], dtype="S500"), expectedlen=1000), things seem to go ok.

**Comment by FrancescElies** [comment]
Though slightly different we had a similar issue with changing types to ndarray at https://github.com/Blosc/bcolz/issues/61
The code above printed no 'oops' for me, which `bcolz` version are you using (v0.11 in my case)?

**Comment by mpage38** [comment]
I had this problem with bcolz 0.9.0. With bcolz 0.11.0, there is no problem. BTW, I struggled to install bcolz 0.11.0. I had to first to update setuptools. And then:

`pip install bcolz` gave me:
Collecting bcolz
  Using cached bcolz-0.11.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in c:\anaconda\envs\py34\lib\site-packages (from bcolz)
Installing collected packages: bcolz
  Running setup.py install for bcolz
...
      File "C:\Anaconda\envs\py34\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\egg_info.py", line 232, in append
      File "C:\Anaconda\envs\py34\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/tmp/bcolz/bcolz/carray_ext.pyx' cannot be absolute

But `python setup.py build_ext --inplace` worked for me.

**Comment by FrancescAlted** [comment]
Hmm, that's weird.  I just installed bcolz 0.11 from conda and everything works well.  Any reason you are not using the conda package on top of your Anaconda installation?

**Comment by FrancescElies** [comment]
With conda in a fresh new environment I could install bcolz, the only problem I had was manually installing mock after installing bcolz. A fix was merged in https://github.com/Blosc/bcolz/pull/253, I guess then in the future should be fine.

**Comment by FrancescAlted** [comment]
Ok.  Seems like a 0.11.1 should be released soon.

**Comment by BrenBarn** [comment]
I am still having the above pip issue ("path cannot be absolute") when trying to install 0.11.3.  It appears the problem is that the SOURCES.txt somehow includes an absolute path to `/tmp/bcolz/bcolz/carray_ext.pyx`.  It seems other projects have had similar issues.  [This issue](https://github.com/behave/behave/issues/28) suggests the problem may be due to some sort of misconfigured build environment.  Should I raise a separate issue for this?

**Comment by FrancescElies** [comment]
The pip issue you're having, is also on a windows machine?

Right, let's open a new issue, could you do that? Thanks

**Comment by FrancescElies** [comment]
@mpage38
Once a separate issue is open, could you close this one if you no longer have problems with appending strings to a carray?

**Comment by FrancescAlted** [comment]
The installation issue is being discussed in #266 so closing.
